[workspace]
members = ["libmemetendo", "memetendo", "web-memetendo"]
default-members = ["memetendo"]

[profile.dev]
opt-level = 1

[profile.release]
lto = true

[profile.release-dev]
inherits = "release"
debug = true
